# Generated by Django 5.0.6 on 2024-06-14 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firist_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
        ),
    ]
