# Generated by Django 5.0.6 on 2024-06-14 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_main_images_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='firist_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
        ),
    ]
