# Generated by Django 5.0.6 on 2024-06-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cartitem_name_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
    ]
