# Generated by Django 5.0.6 on 2024-06-16 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_orderitem_size_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
        ),
    ]
