# Generated by Django 5.0.6 on 2024-06-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
