# Generated by Django 5.0.6 on 2024-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Out for delivary', 'Out For Delivary'), ('deliverd', 'Deliverd')], default='Pending', max_length=20),
        ),
    ]
