# Generated by Django 5.0.6 on 2024-06-16 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='firis_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
