# Generated by Django 5.0.6 on 2024-06-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_orderitem_address_orderitem_firis_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='firis_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone_number',
        ),
    ]
