# Generated by Django 5.0.6 on 2024-06-18 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_orderitem_address_remove_orderitem_firis_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='additional_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
        ),
    ]
