# Generated by Django 5.0.6 on 2024-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_orderitem_additional_info_orderitem_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='additional_info',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='company_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='first_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
