# Generated by Django 5.0.6 on 2024-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_cartitem_size_alter_orderitem_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
